### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by vicpuntnl** [ios-control/ios-sim#131]
I got the following error:

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ios-sim"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.7
npm ERR! code ELIFECYCLE

npm ERR! ios-sim@3.0.0 preinstall: `rake build`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ios-sim@3.0.0 preinstall script.
npm ERR! This is most likely a problem with the ios-sim package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rake build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-sim
npm ERR! There is likely additional logging output above.

**Comment by JasPanesar** [comment]
I continued to experience this problem.  Clean install of Yosemite.  
I was able to get it working by doing the following.  Instead of only installing the Xcode Command line tools, I installed xcode completely from the app store.

Afterwards, I `xcode-select -p` to confirm that xcode command line tools were present, and tried an `xcode-select --install` which also stated the same.

From that point, attempting to `npm install -g ios-sim` gave a different error that simply required me to start up xcode, accept the terms and conditions, let it install some components, and try the command again.  I also read that completing a `sudo npm install-g ios-sim` may be required but ymmv.  

Thanks everyone.
